from pathlib import Path
import argparse
import pandas as pd

ROOT = Path(__file__).resolve().parent
PROC = ROOT / "data" / "processed"

TEMPLATE = """# Cycle-Life Report — {cell}

**Q₀ (Ah):** {q0:.3f}  
**Fade slope:** {slope:.4f}% / cycle  
**Estimated cycles to 80%:** {rul:.0f}

## Key Plots
- Capacity vs Cycle: `data/processed/plot_capacity.png`
- CE vs Cycle: `data/processed/plot_ce.png`

## First 10 cycles (features)
{table}

*Generated by pipeline.py and step14_report.py*
"""

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cell", required=True, help="Cell ID used with pipeline.py (e.g., ARBIN01)")
    args = p.parse_args()

    summary_path = PROC / f"{args.cell}_summary.csv"
    feat_path = PROC / f"{args.cell}_features_full.csv"
    out_md = PROC / f"{args.cell}_report.md"

    if not summary_path.exists():
        raise SystemExit(f"Missing: {summary_path} (run pipeline first)")
    if not feat_path.exists():
        raise SystemExit(f"Missing: {feat_path} (run pipeline first)")

    s = pd.read_csv(summary_path).iloc[0]
    df = pd.read_csv(feat_path).sort_values("cycle_index").head(10)

    # keep a compact table
    show = df[["cycle_index","Q_dis_Ah","CE","E_dis_Wh","IR_C2_ohm","dQdV_peak_V","dQdV_shift_mV"]].copy()
    # round for readability
    show = show.round({
        "Q_dis_Ah": 3, "CE": 4, "E_dis_Wh": 3, "IR_C2_ohm": 4, "dQdV_peak_V": 3, "dQdV_shift_mV": 1
    })
    table_md = show.to_markdown(index=False)

    text = TEMPLATE.format(
        cell=args.cell,
        q0=s.get("Q0_Ah", float("nan")),
        slope=s.get("fade_slope_pct_per_cycle", float("nan")),
        rul=s.get("cycles_to_80pct", float("nan")),
        table=table_md
    )

    out_md.write_text(text, encoding="utf-8")
    print("Wrote:", out_md)

if __name__ == "__main__":
    main()
